#!/usr/bin/env python3
"""Maquina virtual da MPL:
  ./executar programa.mplb
"""
import sys

from mplc.principal import main

if __name__ == '__main__':
    sys.exit(main(['--rodar'] + sys.argv[1:]))
